---
language: python
python: 3.7
dist: bionic

before_install:
    - sudo apt-get update -qq

install:
    # Install Ansible
    - pip install ansible

script:
    - ansible-galaxy install leesoh.dnscat2 -vv
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local
    - dnscat --help

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
